#+title: 01 Current SEO Best Practices
#+author: Sajid Mahmood
#+source: Search Engine Optimization (SEO) Specialization by UCDavis
#+include: Introduction to Google SEO
#+week: Week 02
#+date: <2022-06-22 Wed>
#+options: toc:2

* Current SEO Best Practices

** Introduction to Search Engine Algorithms

All search engines share the goal of providing relevant, timely information.

- As an SEO, our job is to look for the factors and optimize our website according to those which affects an algorithms.
- Some factors are verified, some are secretive.
- Moz, an SEO tool provides lists of possible factors, an algo looks for, every year.
- Google algos, Panda, Florida, caffeine. There constant updates and shift using modern technology by algos to provide better results.
- Over 500 updates annually to Google algos. Only small percent of that updates are released, other info remain vague.

*** MOZcast

An SEO algo tool created by MOZ, which is based upon turbulence.

"Turbulence means high ranking fluctuations, represented by temperature changes"
